import React from 'react';
import { useNavigate } from 'react-router-dom';

const UserDash = () => {
  const navigate = useNavigate();

  // Dummy data for statistics
  const stats = [
    { title: "Total Users", value: "1,234", change: "+12%", color: "bg-gray-500" },
    { title: "Active Users", value: "987", change: "+8%", color: "bg-gray-600" },
    { title: "Pending Requests", value: "56", change: "-3%", color: "bg-gray-500" },
    { title: "Reports Generated", value: "45", change: "+20%", color: "bg-gray-600" },
  ];

  // Dummy data for recent activity
  const recentActivity = [
    { id: 1, action: "User John Doe created", timestamp: "2 hours ago" },
    { id: 2, action: "Report generated by Jane Smith", timestamp: "5 hours ago" },
    { id: 3, action: "User Alice Johnson updated", timestamp: "1 day ago" },
    { id: 4, action: "New role added: Examiner", timestamp: "2 days ago" },
  ];

  return (
    <div className="min-h-screen bg-gray-100 flex">
      {/* Sidebar */}
      <div className="w-64 bg-white shadow-lg p-6">
  <h2 className="text-xl font-semibold mb-6 text-black">Menu</h2>
  <nav>
    <ul className="space-y-4">
      <li>
        <button
          onClick={() => navigate('/UserManagement')}
          className="w-full text-left p-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors"
        >
          Create Users
        </button>
      </li>
      <li>
        <button
          onClick={() => navigate('/ActiveUsers')}
          className="w-full text-left p-2 bg-green-500 hover:bg-green-600 text-white rounded-lg transition-colors"
        >
          View Active Users
        </button>
      </li>
      <li>
        <button
          onClick={() => navigate('/Ureports')}
          className="w-full text-left p-2 bg-purple-500 hover:bg-purple-600 text-white rounded-lg transition-colors"
        >
          Reports
        </button>
      </li>
      <li>
        <button
          onClick={() => navigate('/ManageRoles')}
          className="w-full text-left p-2 bg-red-500 hover:bg-red-600 text-white rounded-lg transition-colors"
        >
          Manage Roles
        </button>
      </li>
    </ul>
  </nav>
</div>

      {/* Main Content */}
      <div className="flex-1 p-8">
        {/* Heading */}
        <h1 className="text-3xl font-bold mb-8 text-black text-center">User Details</h1>

        {/* Statistics Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-8 w-full">
          {stats.map((stat, index) => (
            <div
              key={index}
              className={`${stat.color} p-6 rounded-lg shadow-md text-white`}
            >
              <h2 className="text-xl font-semibold">{stat.title}</h2>
              <p className="text-2xl font-bold">{stat.value}</p>
              <p className="text-sm">{stat.change} from last month</p>
            </div>
          ))}
        </div>

       

        {/* Recent Activity */}
        <div className="bg-white p-6 rounded-lg shadow-md mb-8 w-full text-left">
          <h2 className="text-xl font-semibold mb-4">Recent Activity</h2>
          <div className="space-y-4">
            {recentActivity.map((activity) => (
              <div key={activity.id} className="border-b border-gray-200 pb-4">
                <p className="text-gray-800">{activity.action}</p>
                <p className="text-sm text-gray-500">{activity.timestamp}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Charts Section (Placeholder) */}
        <div className="bg-white p-6 rounded-lg shadow-md w-full">
          <h2 className="text-xl font-semibold mb-4">User Activity Overview</h2>
          <div className="h-64 bg-gray-200 rounded-lg flex items-center justify-center text-gray-500">
            Chart Placeholder (e.g., Bar Chart, Pie Chart)
          </div>
        </div>
      </div>
    </div>
  );
};

export default UserDash;